jedi/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('jedi_academy.urls', namespace="academy"))
]

jedi_academy/urls.py
from django.conf.urls import url, include

from .views import IndexView
from .views import JediChoice, JediPadawans, JediGo
from .views import CandidateCreate, CandidateDetail, CandidateExam

from .views import JediListView, JediListViewActive

jedi_urls = [
    url(r'list$', JediListView.as_view(), name='list_all'),
    url(r'active$', JediListViewActive.as_view(), name='list_active'),
    url(r'(?P<pk>[0-9]+)/padawans/$', JediPadawans.as_view(), name='padawans'),
    url(r'(?P<pk>[0-9]+)/go/(?P<cand_pk>[0-9]+)$', JediGo.as_view(), name='go'),
    url(r'^$', JediChoice.as_view(), name='choice'),
]

candidate_urls = [
    url(r'create/$', CandidateCreate.as_view(), name='create'),
    url(r'(?P<pk>[0-9]+)/$', CandidateDetail.as_view(), name='detail'),
    url(r'(?P<pk>[0-9]+)/exam/$', CandidateExam.as_view(), name='exam'),
]

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^jedi/', include(jedi_urls, namespace='jedi')),
    url(r'^candidate/', include(candidate_urls, namespace='candidate')),
]

jedi_academy/models.py
from django.db import models
from django.core.mail import send_mail
from django.conf import settings

import hashlib


class Planet(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='name')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Planet'
        verbose_name_plural = 'Planets'


class Jedi(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='name')
    training_planet = models.ForeignKey(Planet, verbose_name='planet')

    def add_padawan(self, candidate):
        if self.candidate_set.count() < 3:
            candidate.is_padawan = True
            self.candidate_set.add(candidate)
            candidate.save()
            send_mail(
                    'Candidates notice', 'You are Padawan now.',
                    settings.FROM_EMAIL, [candidate.email]
            )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Jedi'
        verbose_name_plural = 'Jedies'


class Candidate(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='name')
    life_planet = models.ForeignKey(Planet, verbose_name='planet')
    age = models.PositiveIntegerField(verbose_name='age')
    email = models.EmailField(unique=True, verbose_name='e-mail')
    is_padawan = models.BooleanField(default=False, editable=False)
    padawans_room = models.ForeignKey(
        Jedi, blank=True, null=True, verbose_name='jedi')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Candidate'
        verbose_name_plural = 'Candidates'


class OrderCode(models.Model):
    code = models.CharField(
        max_length=64,
        unique=True,
        verbose_name='order`s code'
    )

    def save(self, *args, **kwargs):
        if not self.code and not self.pk:
            super(OrderCode, self).save(*args, **kwargs)
            self.code = hashlib.sha256(str(self.pk).encode('utf-8')).hexdigest()
        super(OrderCode, self).save(*args, **kwargs)

    def __str__(self):
        return self.code

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'


class Question(models.Model):
    code = models.ForeignKey(OrderCode)
    content = models.CharField(max_length=255, verbose_name='content')

    def __str__(self):
        return self.content

    class Meta:
        ordering = ('content',)
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'


class Exam(models.Model):
    candidate = models.ForeignKey(Candidate, verbose_name='candidate')
    question = models.ForeignKey(Question, verbose_name='question')
    answer = models.NullBooleanField(verbose_name='question')

    def __str__(self):
        return self.question.content + ' ' + str(self.answer)

    class Meta:
        ordering = ('candidate',)
        verbose_name = 'Exam'
        verbose_name_plural = 'Exams'

jedi_academy/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Jedi, Candidate, Exam, OrderCode


class JediChoiceForm(forms.Form):
    jedi = forms.ModelChoiceField(
        label='Jedi name',
        queryset=Jedi.objects.all()
    )


class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = ('name', 'life_planet', 'age', 'email')


class ExamForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(ExamForm, self).__init__(*args, **kwargs)
        for question in OrderCode.objects.last().question_set.all():
            field_name = 'question_%s' % question.pk
            self.fields[field_name] = forms.NullBooleanField(
                label=question.content, required=True)

    def save(self, candidate_pk):
        data = self.cleaned_data
        for key, value in data.items():
            exam = Exam.objects.get_or_create(
                candidate_id=int(candidate_pk),
                question_id=int(key.replace('question_', '')))[0]
            exam.answer = value
            exam.save()

jedi_academy/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, View, DetailView, ListView
from django.views.generic.edit import FormView
from django.db.models import Count

from .models import Candidate, Jedi
from .forms import JediChoiceForm, CandidateForm, ExamForm


class IndexView(TemplateView):
    template_name = 'jedi_academy/index.html'


class JediChoice(FormView):
    template_name = 'jedi_academy/jedi_choice.html'
    form_class = JediChoiceForm

    def form_valid(self, form):
        jedi = form.cleaned_data.get('jedi')
        self.request.session['jedi_pk'] = jedi.pk
        return redirect('academy:jedi:padawans', pk=jedi.pk)


class JediPadawans(View):

    def get(self, request, pk):
        jedi = get_object_or_404(Jedi, pk=pk)
        candidates = Candidate.objects.filter(
            life_planet=jedi.training_planet,
            is_padawan=False
        )
        return render(
            request,
            'jedi_academy/jedi_padawans.html', {'candidates': candidates}
        )


class JediGo(View):
    template_name = 'jedi_academy/warning.html'
    msg = 'Слишком много подаванов. Вы не справетись, мастер.'

    def get(self, request, pk, cand_pk):
        candidate = get_object_or_404(Candidate, pk=cand_pk)
        jedi = get_object_or_404(Jedi, pk=pk)
        if jedi.candidate_set.count() < 3:
            jedi.add_padawan(candidate)
            self.msg = "У Вас новый падаван."
        return render(
            request,
            self.template_name,
            {'msg': self.msg}
        )


class CandidateDetail(DetailView):
    model = Candidate
    template_name = 'jedi_academy/cand_detail.html'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(CandidateDetail, self).get_context_data(**kwargs)
        context['jedi_pk'] = self.request.session.get('jedi_pk')
        return context


class CandidateCreate(FormView):
    template_name = 'jedi_academy/cand_create.html'
    form_class = CandidateForm

    def form_valid(self, form):
        candidate = form.save()
        return redirect('academy:candidate:exam', pk=candidate.pk)


class CandidateExam(FormView):
    template_name = 'jedi_academy/cand_exam.html'
    form_class = ExamForm

    def form_valid(self, form):
        form.save(self.kwargs['pk'])
        return render(self.request, 'jedi_academy/warning.html', {'msg': 'Успех'})

    def get_context_data(self, **kwargs):
        context = super(CandidateExam, self).get_context_data(**kwargs)
        context['cand_pk'] = self.kwargs['pk']
        return context


# Extends version


class JediListView(ListView):
    template_name = 'jedi_academy/jedi_list.html'
    context_object_name = 'items'

    def get_queryset(self):
        return Jedi.objects.annotate(
            Count('candidate')).order_by('-candidate__count', 'name')


class JediListViewActive(ListView):
    template_name = 'jedi_academy/jedi_list.html'
    context_object_name = 'items'

    def get_queryset(self):
        return Jedi.objects.annotate(
            Count('candidate')).filter(
            candidate__count__gt=0).order_by('-candidate__count', 'name')

jedi_academy/templates/jedi_academy/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Jedi Order</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
      integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
</head>
<body>
<div class='container'>
    <div class='row'>
        <div class='col-12'>
            <h2 class='text-center'>Академия джедаев</h2>
            <div class="text-center">
                | <a href='/'>Главная</a>
                | <a href='{% url "academy:jedi:list_all" %}'>Все Джедаи</a>
                | <a href='{% url "academy:jedi:list_active" %}'>Джедаи и падаваны</a> |
            </div>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {% block content%}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

jedi_academy/templates/jedi_academy/cand_create.html
{% extends 'jedi_academy/base.html' %}

{% block content %}
    <div class='text-center'>
        <h4>Заполни свои данные, кандидат!</h4>
        <form action='{% url 'academy:candidate:create' %}', method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit' class='btn btn-success'>Далее</button>
        </form>
    </div>
{% endblock %}

jedi_academy/templates/jedi_academy/cand_detail.html
{% extends 'jedi_academy/base.html' %}

{% block content %}

    <div class="text-center"> <span><strong>Информация о кондидате</strong></span> </div>
    <p><strong>Планета:</strong> {{ candidate.life_planet.name }}</p>

    <p><strong>Возраст:</strong> {{ candidate.age }}</p>

    <p><strong>Email:</strong> {{ candidate.email }}</p>
    <hr />

    <div class="text-center"> <span><strong>Результаты теста</strong></span> </div>
    <table class='table'>
        {% for exam in candidate.exam_set.all %}
            <tr>
                <td>{{ exam.question.content }}</td>
                <td>{{ exam.answer }}</td>
            </tr>
        {% endfor %}
    </table>
    <a class='btn btn-primary' href='{% url 'academy:jedi:go' jedi_pk candidate.pk %}'>Принять на обучение</a>
{% endblock %}

jedi_academy/templates/jedi_academy/cand_exam.html
{% extends 'jedi_academy/base.html' %}

{% block content %}
    <div class="row">
        <form action='{% url 'academy:candidate:exam' pk=cand_pk %}' method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <button class='btn btn-primary' type='submit'>Сдать</button>
        </form>
    </div>
{% endblock %}

jedi_academy/templates/jedi_academy/index.html
{% extends 'jedi_academy/base.html' %}

{% block content %}
        <div class="text-center">
            <a class='btn btn-secondary' href='{% url "academy:jedi:choice" %}'>Для Джедаев</a>
            <a class='btn btn-secondary' href='{% url "academy:candidate:create" %}'>Для кандидатов</a>
        </div>
{% endblock %}

jedi_academy/templates/jedi_academy/jedi_choice.html
{% extends 'jedi_academy/base.html' %}

{% block content %}
    <div class="text-center">
        <h3>Кто вы мастер?</h3>
        <form action='{% url "academy:jedi:choice" %}' method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <button type='submit' class='btn btn-success'>Далее</button>
        </form>
    </div>
{% endblock %}

jedi_academy/templates/jedi_academy/jedi_list.html
{% extends 'jedi_academy/base.html' %}

{% block content %}
    <div class="text-center">

        <p><span>Джедай</span> | <span>Падаваны</span></p>
            {% for item in items %}
            <p>
                <span>{{ item.name }}</span> -
                <span>{{ item.candidate_set.count }}</span>
            </p>
            {% endfor %}
    </div>

{% endblock %}

jedi_academy/templates/jedi_academy/jedi_padawans.html
{% extends 'jedi_academy/base.html' %}

{% block content %}
    <div class="text-center">
        <span>Готовые к обучению</span>
        {% for candidate in candidates %}
            <p>
                <a href='{% url 'academy:candidate:detail' pk=candidate.id %}'>{{ candidate.name }}</a>
            </p>
        {% empty %}
            <span>Нет способных юнлингов</span>
        {% endfor %}
    </div>
{% endblock %}

jedi_academy/templates/jedi_academy/warning.html
{% extends 'jedi_academy/base.html' %}

{% block content %}
    <div class="text-center">
        {{ msg }}
    </div>
{% endblock %}